[tool.poetry]
name = "xcore"
version = "0.1.0"
description = "for base html core app"
authors = ["Eliezer Traore <68350805+traoreera@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
sqlalchemy = ">=2.0.41,<3.0.0"
python-dotenv = ">=1.1.0,<2.0.0"
alembic = ">=1.16.1,<2.0.0"
passlib = { extras = ["bcrypt"], version = ">=1.7.4,<2.0.0" }
flake8 = ">=7.2.0,<8.0.0"
apscheduler = ">=3.11.0,<4.0.0"
pyotp = ">=2.9.0,<3.0.0"
pydantic = { extras = ["email"], version = ">=2.11.7,<3.0.0" }
python-jose = ">=3.4.0,<4.0.0"
pillow = ">=11.2.1,<13.0.0"
qrcode = { extras = ["pil"], version = ">=8.2,<9.0" }
paho-mqtt = ">=2.1.0,<3.0.0"
psutil = ">=7.0.0,<8.0.0"
rich = ">=14.0.0,<15.0.0"
gunicorn = ">=23.0.0,<24.0.0"
black = ">=25.1.0,<26.0.0"
watchdog = ">=6.0.0,<7.0.0"
markdown = ">=3.8.2,<4.0.0"
mysql-connector-python = "^9.4.0"
toml = "^0.10.2"
uvicorn = "^0.38.0"
bcrypt = "4.0.1"
pip = "==26.0.1"
user-agents = "^2.2.0"
jinja2 = "^3.1.6"
pydantic-settings = "^2.12.0"
psycopg2 = "^2.9.11"
aiosqlite = "^0.22.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"
black = "^25.9.0"
flake8 = "^7.3.0"
autoflake = "^2.3.1"
isort = "^6.1.0"
autopep8 = "^2.3.2"
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
httpx = "^0.28.1"
faker = "^37.8.0"
pytest-cov = "^7.0.0"
bandit = "^1.8.6"
fastapi = "^0.118.2"
aiocache = "^0.12.3"
redis = {extras = ["hiredis"], version = "^7.0.0"}
aiohttp = "^3.13.3"


[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
myst-parser = "^5.0.0"
sphinx-copybutton = "^0.5.2"
sphinx-rtd-theme = "^3.1.0"
linkify-it-py = "^2.0.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88



[tool.poetry.scripts]
xcore = "xcore.cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xcore*"]