[tool.poetry]
name = "xcore"
version = "0.1.0"
description = "for base html core app"
authors = ["Eliezer Traore <68350805+traoreera@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]

# environment
python-dotenv = ">=1.1.0,<2.0.0"

# database migration
alembic = ">=1.16.1,<2.0.0"

# tools
apscheduler = ">=3.11.0,<4.0.0"
rich = ">=14.0.0,<15.0.0"
watchdog = ">=6.0.0,<7.0.0"
markdown = ">=3.8.2,<4.0.0"
pillow = ">=11.2.1,<13.0.0"
psutil = ">=7.0.0,<8.0.0"

toml = "^0.10.2"
uvicorn = "^0.38.0"

# security
bcrypt = "4.0.1"
passlib = { extras = ["bcrypt"], version = ">=1.7.4,<2.0.0" }
python-jose = ">=3.4.0,<4.0.0"


# python
pip = "==26.0.1"
python = ">=3.11,<4.0"

# http
user-agents = "^2.2.0"


# data validation
pydantic = { extras = ["email"], version = ">=2.11.7,<3.0.0" }
pydantic-settings = "^2.12.0"

# database
psycopg2 = "^2.9.11"
aiosqlite = "^0.22.1"
mysql-connector-python = "^9.4.0"
sqlalchemy = ">=2.0.41,<3.0.0"
fastapi = "^0.118.2"
aiocache = "^0.12.3"
redis = {extras = ["hiredis"], version = "^7.0.0"}


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.3.0"
black = "^25.9.0"
flake8 = "^7.3.0"
autoflake = "^2.3.1"
isort = "^6.1.0"
autopep8 = "^2.3.2"
pytest = "^8.4.2"
pytest-asyncio = "^1.2.0"
httpx = "^0.28.1"
faker = "^37.8.0"
pytest-cov = "^7.0.0"
bandit = "^1.8.6"
aiohttp = "^3.13.3"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.7.3"
mkdocs-minify-plugin = "^0.8.0"
mkdocstrings = "^1.0.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 88



[tool.poetry.scripts]
xcore = "xcore.cli.main:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xcore*"]